"""add_updated_at_to_api_keys

Revision ID: e5443e4829fe
Revises: 6f7bb5f8c70e
Create Date: 2026-04-02 15:44:19.349633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5443e4829fe'
down_revision: Union[str, None] = '6f7bb5f8c70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'updated_at')
    # ### end Alembic commands ###
